    ("Don't watch the clock; do what it does. Keep going.", "Sam Levenson"),
    ("Everything you've ever wanted is on the other side of fear.", "George Addair"),
    ("You are never too old to set another goal or to dream a new dream.", "C.S. Lewis"),
    ("The secret of getting ahead is getting started.", "Mark Twain"),
    ("Your limitation—it's only your imagination.", "Unknown"),
    ("Push yourself, because no one else is going to do it for you.", "Unknown"),
    ("Great things never come from comfort zones.", "Unknown"),
    ("Dream it. Wish it. Do it.", "Unknown"),
    ("Stay foolish, stay hungry.", "Steve Jobs"),
    ("The harder you work for something, the greater you'll feel when you achieve it.", "Unknown"),
    ("Don't stop when you're tired. Stop when you're done.", "Unknown"),
    ("Wake up with determination. Go to bed with satisfaction.", "Unknown"),
    ("Little things make big days.", "Unknown"),
    ("It's going to be hard, but hard does not mean impossible.", "Unknown"),
    ("Sometimes we're tested not to show our weaknesses, but to discover our strengths.", "Unknown"),
    ("The key to success is to focus on goals, not obstacles.", "Unknown"),
    ("Dream bigger. Do bigger.", "Unknown"),
    ("Work hard in silence, let your success be the noise.", "Frank Ocean"),
    ("If it doesn't challenge you, it won't change you.", "Fred DeVito"),
    ("What you do today can improve all your tomorrows.", "Ralph Marston"),
    ("Don't limit your challenges. Challenge your limits.", "Unknown"),
    ("Hustle until your haters ask if you're hiring.", "Unknown"),
    ("The best time to plant a tree was 20 years ago. The second best time is now.", "Chinese Proverb"),
    ("Act as if what you do makes a difference. It does.", "William James"),
    ("Success usually comes to those who are too busy to be looking for it.", "Henry David Thoreau"),
    ("Opportunities don't happen. You create them.", "Chris Grosser"),
    ("Don't be afraid to give up the good to go for the great.", "John D. Rockefeller"),
    ("I find that the harder I work, the more luck I seem to have.", "Thomas Jefferson"),
    ("The road to success and the road to failure are almost exactly the same.", "Colin R. Davis"),
    ("It is never too late to be what you might have been.", "George Eliot"),
]

# Path to save tasks
TASKS_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dashboard_tasks.json")

